{{ $listF := (cslice "** O que seria uma férias perfeita para você?**\n> `A.` Experimentar coisas novas que não tinha tempo\n> `B.` Ficar isolado na minha casa, longe de tudo e todos\n> `C.` Passar as férias em um lugar paradisíaco\n> `D.` Viajar pelo mundo conhecendo novos lugares" "**Se você pudesse escolher um superpoder, qual seria?**\n> `A.` Aprender rapidamente qualquer habilidade\n> `B.` Ficar invisível em momentos oportunos\n> `C.` Ler o pensamento dos outros\n> `D.` Viajar no tempo, tanto passado quanto futuro" "**Você está com pressa, porém seu vizinho bate na porta pedindo ajuda, o que você faria?**\n> `A.` Vai até a casa de outro vizinho perguntar se ele pode ajudar\n> `B.` Tiraria um pouco do seu tempo para tentar ajudar \n> `C.` Iria fingir que nem ouviu e ignora ajudar\n> `D.` Pede desculpas, mas fala que não tem tempo" "**O que seria um dia perfeito para você?**\n> `A.` Comer o dia todo, tudo aquilo que você mais gosta, sem se preocupar com engordar\n> `B.` Passar o dia dormindo, sem se preocupar com nada ao redor\n> `C.` Passar a tarde com os amigos se divertindo\n> `D.` Acordar cedo, e resolver todas as suas pendências") }}
{{ $listS := (cslice "**O que te deixaria mais feliz?**\n> `A.` Poder passar o dia dormindo\n> `B.` Poder comer de tudo sem engordar\n> `C.` Ser rico e poder comprar tudo que eu quiser\n> `D.` Descansar em um lugar calmo e paradisíaco" "**Se você e seu melhor amigo(a) acabam discutindo, você...**\n> `A.` Peço desculpas e reconheço meu erro\n> `B.` Espero ele(a) tomar atitude de pedir desculpas, caso não peça, vou lá e peço, mesmo estando certo(a)\n> `C.` Não faço nada, pois ele(a) que começou a briga, então ele que deve pedir desculpas\n> `D.` Pede desculpas só para quebrar o gelo da conversa" "**Como seu quarto é frequentemente?**\n> `A.` No brilho, tudo limpinho e organizado, odeio bagunça\n> `B.` Uma bagunça, tudo jogado e cama desforrada\n> `C.` Às vezes bagunçado, as vezes limpo e organizado\n> `D.` Não é arrumado, porém eu sei onde tudo está localizado na minha bagunça" "**Se você ficasse milionário da noite pro dia, o que você faria?**\n> `A.` Ajudaria alguém da família ou alguém que precisasse mais do que você\n> `B.` Investiria tudo para tentar aumentar a minha fortuna\n> `C.` Gastaria com viagens, roupas e qualquer coisa que meu dinheiro pudesse comprar\n> `D.` Esconderia com medo que alguém fosse te roubar") }}
{{ $listT := (cslice "**Qual seria a pior situação que você passaria em uma praia?**\n> `A.` Me afogar no meio da multidão\n> `B.` Derrubar o picolé que você acabou de comprar na areia\n> `C.` Tropeçar e cair enquanto joga futebol de areia\n> `D.` Dormir enquanto se bronzeia" "**Se você pudesse ouvir apenas um tipo de música para o resto da sua vida, o que você escolheria?**\n> `A.` Algo que você conhece bem e houve todos os dias\n> `B.` Algo que me deixasse empolgado o dia todo\n> `C.` Algo nostálgico que eu já tenha escutado várias vezes\n> `D.` Algo que me fizesse relaxar" "**Sua casa dos sonhos certamente teria?**\n> `A.` Uma lareira gigante, que deixasse seu ambiente sempre quentinho\n> `B.` Uma sala de estar enorme com muita luz natural, perfeita para curti o dia\n> `C.` Uma piscina enorme, capaz de acomodar todos os seus amigos\n> `D.` Um quarto do tamanho ideal, com uma cama estupidamente confortável" "**Se você pudesse ter um companheiro animal pro resto da vida, qual você escolheria?**\n> `A.` Um cachorro\n> `B.` Um porco\n> `C.` Um coelho\n> `D.` Um hamster") }}
 
{{ $pollF := (index (shuffle $listF) 0) }}
{{ $pollS := (index (shuffle $listS) 0) }}
{{ $pollT := (index (shuffle $listT) 0) }}
 
{{ $embed := cembed
"description" (joinStr "" "<:hypesquad:762109310980587520> **HYPESQUAD DO GARTIC [BETA]**\n\nBem-vindo ao <@&762105962583687228>, " (.Message.Author).Mention ",  você terá um minuto para responder as perguntas e ingressar em uma equipe. Para responder basta digitar: \n**-hype** `<resposta 1>` `<resposta 2>` `<resposta 3>`. \n\n:one: " $pollF "\n\n:two: " $pollS "\n\n:three: " $pollT )
"color" 14525473
"footer"  (sdict "text" (joinStr "" "⚠ Suas respostas irão influenciar na escolha do seu HypeSquad"))
}}
{{ $mID := sendMessageRetID nil $embed}}
{{$silent := execAdmin "giverole" (.User.ID) 762105962583687228 "-d 60s" }}
{{ deleteTrigger 0 }}
{{ deleteMessage nil $mID 60 }}